var files_dup =
[
    [ "block.cc", "block_8cc.html", null ],
    [ "block.hh", "block_8hh.html", "block_8hh" ],
    [ "coin.cc", "coin_8cc.html", null ],
    [ "coin.hh", "coin_8hh.html", "coin_8hh" ],
    [ "fenster.h", "fenster_8h.html", "fenster_8h" ],
    [ "finder.hh", "finder_8hh.html", "finder_8hh" ],
    [ "game.cc", "game_8cc.html", null ],
    [ "game.hh", "game_8hh.html", "game_8hh" ],
    [ "geometry.cc", "geometry_8cc.html", "geometry_8cc" ],
    [ "geometry.hh", "geometry_8hh.html", "geometry_8hh" ],
    [ "interactables.cc", "interactables_8cc.html", null ],
    [ "interactables.hh", "interactables_8hh.html", "interactables_8hh" ],
    [ "main.cc", "main_8cc.html", "main_8cc" ],
    [ "mario.cc", "mario_8cc.html", null ],
    [ "mario.hh", "mario_8hh.html", "mario_8hh" ],
    [ "platform.cc", "platform_8cc.html", "platform_8cc" ],
    [ "platform.hh", "platform_8hh.html", "platform_8hh" ],
    [ "start_screen.cc", "start__screen_8cc.html", null ],
    [ "start_screen.hh", "start__screen_8hh.html", "start__screen_8hh" ],
    [ "text.cc", "text_8cc.html", "text_8cc" ],
    [ "text.hh", "text_8hh.html", "text_8hh" ],
    [ "utils.cc", "utils_8cc.html", "utils_8cc" ],
    [ "utils.hh", "utils_8hh.html", "utils_8hh" ],
    [ "window.cc", "window_8cc.html", null ],
    [ "window.hh", "window_8hh.html", "window_8hh" ]
];